### ISSUE TITLE
Strips whitespace from description lists

### ISSUE THREAD

**Issue by Seirdy** [mdigger/goldmark-formatter#1]
## Expected behavior

mdfmt does not remove whitespace from the following text:

``` markdown
Term
: Description of term

Term 2
: Description of term 2

Term 3
: Description of term 3
```

## Actual behavior

mdfmt removes the blank lines between the terms:

``` markdown
Term
: Description of term
Term 2
: Description of term 2
Term 3
: Description of term 3
```

Running it again causes another whitespace removal:

``` markdown
Term
: Description of term Term 2
: Description of term 2 Term 3
: Description of term 3
```

## Severity

Goldmark relies on blank lines between description-term and description-details pairs. Formatting a file with mdmft will make all `<dl>` elements appear malformed upon conversion to HTML.

## Version information

Running mdfmt built from mdigger/goldmark-formatter@be5daf68 compiled with Go 1.17.

**Comment by mdigger** [comment]
fix 23e60f5
